In [1]:
#input adjacency matrix
import numpy as np
L = np.array([[0,1,1,0,0,0],[0,0,0,0,0,0],[1,1,0,0,1,0],[0,0,0,0,1,1],[0,0,0,1,0,1],[0,0,0,1,0,0]])
print(L)
n=len(L)

[[0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 1 0 0]]


In [2]:
L_T = np.transpose(L)
H=[]
A=[]
H.append(np.ones((n,1)))
A.append(np.ones((n,1)))
e=0.05
c=1
k=0
while c:
    H.append((L.dot(L_T).dot(H[k])))
    H[k+1]=H[k+1]/np.linalg.norm(H[k+1])
    a=abs((H[k+1]-H[k]))<e
    stop = a.all()
    if stop:
        c=0

    k=k+1
c=1
k=0
while c:
    A.append((L_T.dot(L).dot(A[k])))
    A[k+1]=A[k+1]/np.linalg.norm(A[k+1])
    a=abs((A[k+1]-A[k]))<e
    stop = a.all()
    if stop:
        c=0

    k=k+1

In [3]:
#Hubs
for i in range(len(H)):
    print('--------------------------------')
    print(f'Iteration {i}')
    
    print(H[i])
    print('--------------------------------')

--------------------------------
Iteration 0
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
--------------------------------
--------------------------------
Iteration 1
[[0.35856858]
 [0.        ]
 [0.5976143 ]
 [0.47809144]
 [0.47809144]
 [0.23904572]]
--------------------------------
--------------------------------
Iteration 2
[[0.32781098]
 [0.        ]
 [0.65562195]
 [0.50661696]
 [0.41721397]
 [0.17880599]]
--------------------------------
--------------------------------
Iteration 3
[[0.3219924 ]
 [0.        ]
 [0.68789287]
 [0.51226064]
 [0.37321847]
 [0.14636018]]
--------------------------------


In [4]:
#authority
for i in range(len(A)):
    print('--------------------------------')
    print(f'Iteration {i}')
    
    print(A[i])
    print('--------------------------------')

--------------------------------
Iteration 0
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
--------------------------------
--------------------------------
Iteration 1
[[0.31980107]
 [0.53300179]
 [0.21320072]
 [0.31980107]
 [0.53300179]
 [0.42640143]]
--------------------------------
--------------------------------
Iteration 2
[[0.34045882]
 [0.5237828 ]
 [0.18332398]
 [0.2618914 ]
 [0.57616108]
 [0.41902624]]
--------------------------------
--------------------------------
Iteration 3
[[0.35124594]
 [0.52367576]
 [0.17242982]
 [0.22990643]
 [0.59392495]
 [0.40872255]]
--------------------------------
